@extends('layouts.layout')

@section('title')
How I Learned Ukrainian
@endsection

@section('content')

<home :user="user" inline-template>
    <div class="container">

        <header class="entry-header">
            <h1 class="entry-title">How I Learned Ukrainian</h1>
        </header>
        <div class="entry-content">
            <p>One of my highest priorities when I came to Ukraine was to learn Ukrainian, and I would say that I succeeded in that goal. &nbsp;Nowadays, I speak Ukrainian reasonably well and have many friends with whom I speak 100% Ukrainian. &nbsp;Learning Ukrainian didn&rsquo;t &ldquo;just happen&rdquo; from being &ldquo;immersed&rdquo; in the foreign language, and I can tell you that there are many expats who have been here for years longer than I have who can barely string together a sentence in Ukrainian (or Russian for that matter). &nbsp;I learned Ukrainian because I made a conscious effort to learn and practice, including taking a language course when I arrived in Lviv and making an effort to communicate with Ukrainians in Ukrainian language.</p>
            <h2>First steps and taking a Ukrainian language course</h2>
            <p>Before I arrived in Lviv, I signed up for an intensive 3-hour a day with&nbsp;<a href="http://learn-ukrainian.org.ua/">Learn Ukrainian</a>, a private language school run by Solomija Buk, a philology professor at the University of Lviv (it was the first one I found through Google, and although I don&rsquo;t necessarily recommend it, it&rsquo;s not a bad option per se). &nbsp;I found myself in a class with only one other student (which should not have been surprising &mdash; Ukrainian is not a popular language), a middle-aged ex-military guy named Chuck whose girlfriend was Ukrainian. &nbsp;Since I learned a lot more quickly than Chuck, our class was quickly decomposed into two separate one-on-one courses.</p>
            <p>My private teacher was a recent grad and didn&rsquo;t have much pedagogical training, so I had to teach her how I wanted to be taught, proposing a structure for our classes: &nbsp;We would speak in Ukrainian and just have a regular chat together for the first and last hours of our course, and in the middle we would go through the lessons in her book, focussing in particular on reciting the dialogues. &nbsp;At home, I would read the grammar explanations and vocabulary by myself. &nbsp;I tried to use flashcard systems like&nbsp;<a href="https://apps.ankiweb.net/">Anki</a>, but quickly got bored of it (which was lazy on my part), so I never built flashcards for learning Ukrainian.</p>
            <p>The private teacher provided me with time to practice Ukrainian&nbsp;<em>and</em>&nbsp;gave me a source of new words and grammatical concepts. &nbsp;However, I had the most amazing learning experience with a girl I met outside of the class. &nbsp;When the receptionist at my hostel, a music student named Mariana, learned that I was taking a course to learn Ukrainian, she refused to speak with me in English and insisted that we communicate solely in Ukrainian. &nbsp;She worked the night shift, so every night for about two weeks, we would speak to each other completely in Ukrainian for one or two hours every night before I went to bed. &nbsp;It&rsquo;s important to note that this&nbsp;<em>wasn&rsquo;t&nbsp;</em>a class, we were just having a conversation.</p>
            <p>You might wonder: &nbsp;How the hell was this possible at the beginning of my language learning? &nbsp;I didn&rsquo;t speak Ukrainian! &nbsp;Well, the amazing thing I learned was that I actually did! &nbsp;You can &ldquo;speak&rdquo; and &ldquo;converse&rdquo; in a language, without really &ldquo;knowing&rdquo; the language. &nbsp;We communicated through a combination of body language, facial expression, drawings, and with the new Ukrainian words I was learning every day in my class. &nbsp;I drew heavily on my knowledge of Czech (I lived in Prague for about a year and also learned a lot of Czech, which is a Slavic language that is strikingly similar to Ukrainian in many ways) to understand some of the cognates in Ukrainian language, but what was amazing was that we really could understand each other with a really bare base of actual language knowledge on my part. &nbsp;This two-week period was the perfect combination of book learning and intense conversational practice to learn the basics of a language quickly. By the end of it, I was comfortable having conversations with strangers completely in Ukrainian.</p>
            <h2>Taking my Ukrainian to the streets</h2>
            <p>Whenever I walked around the streets of Lviv, I stuck out quite obviously as a foreigner because I&rsquo;m Asian. &nbsp;This meant that people usually found me to be a source of novelty. &nbsp;Young people, especially, would sometimes wave hello to me when they saw me walking past around the town or in a park. &nbsp;Whenever this happened, I took the opportunity to say hello back. &nbsp;When they discovered that I could speak Ukrainian, they&rsquo;d usually be amazed, and it was a great segue into having a conversation together. &nbsp;After my course was finished, I continued speaking with people around the city in Ukrainian.</p>
            <p>Lviv, like all the nice cities of Europe, is a pedestrian city, easily strollable with people out at all times of the day. &nbsp;Just walking around was enough of a way for me to meet people who were willing to speak to me and let me get some practice in Ukrainian.</p>
            <p>I met my best friend in Lviv by bumping into her at an outdoor bookstall on Ploscha Rynok, at the heart of Lviv. &nbsp;I asked her what she was looking for, and she was amazed to find a foreigner who spoke Ukrainian. &nbsp;She grabbed my hand and practically dragged me to the nearest cafe to hear my story. &nbsp;She told me she was an artist trying to find people who would sell her books, and we ended up meeting multiple times a week to talk about our lives together.</p>
            <h2>Going on adventures</h2>
            <p>One of the great things about living in Lviv is that it&rsquo;s a tourist city, but one oriented primarily towards Ukrainian tourists. &nbsp;This means that is has lots of infrastructure for tourism, especially guided tours. &nbsp;I did a number of weekend tours to the countryside and to the Carpathian mountains, where I was stuck on a bus as the only foreigner and&nbsp;<em>had to</em>&nbsp;interact with people in the language.</p>
            <p>I think this is one of the&nbsp;<em>funnest</em>&nbsp;ways to learn a foreign language: &nbsp;going on a tour of the country&nbsp;<em>with</em>&nbsp;tourists from that country. &nbsp;I saw a lot of things that other foreigners don&rsquo;t tend to see, and at the same time, I was approached by friendly Ukrainian tourists who were curious about my story.</p>
            <h2>Lessons from learning Ukrainian</h2>
            <p>I learned a lot about how to learn a language by learning Ukrainian in Lviv. &nbsp;My Ukrainian is still not&nbsp;<em>that</em>&nbsp;good, but I understand now what it takes to learn a language: &nbsp;a lot of time and effort. &nbsp;There are a lot of tricks you can use, but the two main points of learning a language are this: &nbsp;(1) you&nbsp;<em>have</em>&nbsp;to practice by speaking and having conversations in the target language, and (2) practice&nbsp;<em>isn&rsquo;t</em> enough, you also have to constantly improve your vocabulary and grammar by learning from a course, a teacher, or a book. &nbsp;This second point is important, because having conversations with your friends won&rsquo;t naturally improve your abilities unless you are being corrected &mdash; which your friends will be too polite to do&nbsp;</p>
            <p>I hope this post gives you some inspiration for your own Ukrainian language-learning journey! &nbsp;If you have some tips or want to share some of your own experiences with learning Ukrainian, share them in the comments below.</p>
        </div>

    </div>

</home>

@endsection